theme: jekyll-theme-architect
title: Mast
description: Multi-Audience storytelling
plugins:
  - jekyll-relative-links
relative_links:
  enabled: true
  collections: true
include:
  - about.md
  - README.md

